drop table hospitals
create table hospitals(
	x double precision,
	y double precision,
	fid integer primary key,
	id_ integer,
	name_ text,
	address text,
	city text,
	state_ text,
	zip integer,
	zip4 text,
	telephone text,
	type_ text,
	status text,
	population integer,
	county text,
	country_fips text,
	country text,
	latitude double precision,
	longitude double precision,
	naics_code integer,
	naics_desc text,
	web_site text,
	source_date timestamp,
	val_method text,
	val_date timestamp,
	web_site_2 text,
	state_id text,
	alt_name text,
	st_fips text,
	owner_ text,
	ttl_staff integer,
	beds integer,
	trauma text,
	helipad character varying(1))

select *
from hospitals